# Generated by Django 3.2.12 on 2024-04-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename1', models.TextField(blank=True, null=True)),
                ('filename2', models.TextField(blank=True, null=True)),
                ('levenshtein', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('jaccard', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('jarowinkler', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'comparison',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('sha_256', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('malware_name', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('first_bytes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'samples',
                'managed': False,
            },
        ),
    ]
