# Generated by Django 3.2.12 on 2024-04-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APT_sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('malware_name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('first_bytes', models.CharField(max_length=100)),
            ],
        ),
    ]
