# Generated by Django 3.2.12 on 2024-04-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apt_sample',
            table='samples',
        ),
    ]
