# Generated by Django 3.2.12 on 2024-04-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_apt_sample_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('malware_name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('first_bytes', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'samples',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='APT_sample',
        ),
    ]
