# Generated by Django 3.2.12 on 2024-04-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20240401_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename1', models.TextField(blank=True, null=True)),
                ('filename2', models.TextField(blank=True, null=True)),
                ('levenshtein', models.TextField(blank=True, null=True)),
                ('jaccard', models.TextField(blank=True, null=True)),
                ('jarowinkler', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comparison',
                'managed': False,
            },
        ),
    ]
